Update UT61E+_POC.py
Suggested changes to run with python3-hid 0.9.0, because the original code generates:
TypeError: 'hid.device' object does not support the context manager protocol (HIDAPI perhaps now lacks a context manager?)
The changes also fit the hidapi page examples (https://trezor.github.io/cython-hidapi/examples.html)